name: React CI/CD
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Aliyun ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          USERNAME: ${{ secrets.ACR_USERNAME }}
          PASSWORD: ${{ secrets.ACR_PASSWORD }}
      - name: Bulid and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_REGISTRY }}:latest
